---
title: "writeup.rmd"
author: "Cleo Ware"
date: "Fall 2023"
output: html_document
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)  
```

# Introduction

We are looking for correlations in the data.

# Methods

We will be using CanP helper file Num~Num to help us run test on the data we've imported.

# Results



## Graphical Descriptive Results
```{r}
ggplot(data,aes(y=ARM,x=SIMS))+
  geom_point()+
  geom_smooth(method=lm)
ggplot(data,aes(y=GRIP,x=SIMS))+
  geom_point()+
  geom_smooth(method=lm)
ggplot(data,aes(y=ARM+GRIP,x=SIMS))+
  geom_point()+
  geom_smooth(method=lm)
```



## Numerical Descriptive Results

```{r}
cor(SIMS~ARM,data=data)
cor(SIMS~GRIP,data=data)
cor(SIMS~ARM+GRIP,data=data)
```

Model 3 is the best.:)

## Inferential Results

```{r}
model.1 <- lm(SIMS~ARM,data=data)
summary.lm(model.1)
model.2 <- lm(SIMS~GRIP,data=data)
summary.lm(model.2)
model.3 <- lm(SIMS~ARM+GRIP,data=data)
summary.lm(model.3)
```



# Discussion and Conclusion



